export const ADD_DIET_REQUEST = "ADD_DIET_REQUEST" 
export const GET_DIETS_REQUEST = "GET_DIETS_REQUEST"
export const GET_DIETS_SUCCESS = "GET_DIETS_SUCCESS"
export const GET_DIETS_FAILURE = "GET_DIETS_FAILURE"